use ecommerce;
-- to get the all data from table
select * from mytable;
select * from mytable1;
-- updating the column data where null replace into cash
update mytable
set card ='cash'
where card is null;



-- query to get the date and coffee name
select date,coffee_name from mytable;



-- alter column name to price
alter table mytable
rename column money to price;






-- total revenue generated by perticular coffe
select sum(price) as revenue, coffee_name from mytable
group by coffee_name;


select distinct coffee_name ,price from mytable
;

-- average sales on a perticular day 
select date,avg(price) as avg_revenue  from mytable
group by date;



-- highest revenue day
select date,sum(price) as highest_revenue
from mytable
group by date
order by highest_revenue desc limit 1;


-- top 5 best selling coffee
select coffee_name,count(coffee_name) as top_5_coffee
from mytable
group by coffee_name
order by top_5_coffee desc
limit 5;

-- join the two tables

select*from mytable mt
 join make_cost  mc
on mt.coffee_name=mc.coffee_name;


-- profit by coffee
SELECT mt.coffee_name,
       SUM(mt.price - mc.coffee_cost) AS profit
FROM mytable mt
JOIN make_cost mc 
     ON mt.coffee_name = mc.coffee_name
GROUP BY mt.coffee_name
ORDER BY profit DESC;




-- Create a view for daily revenue
CREATE VIEW daily_revenue AS
SELECT date, SUM(price) AS revenue
FROM mytable
GROUP BY date;

-- Use the view
SELECT * FROM daily_revenue ORDER BY revenue DESC;


